name: Build Android APK

on:
  push:
   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip git zip unzip openjdk-17-jdk \
          autoconf libtool pkg-config zlib1g-dev \
          libncurses5-dev libffi-dev libssl-dev

      - name: Install Python dependencies
        run: |
          pip install buildozer cython

      - name: Build APK
        run: |
          buildozer android debug
