name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: kivy/buildozer

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build APK
        run: yes | buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: bin/*.apk
